server:
  servlet:
    context-path: /library-client
  port: 9090
  error:
    include-stacktrace: never

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            authorizationGrantType: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: none
            scope: openid
        provider:
          keycloak:
            issuerUri: ${ISSUER_URI}
            user-name-attribute: name

logging:
  level:
    root: info
    org:
      springframework:
        web: info

library:
  server: ${SERVER_URL}
