spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ea608580c1107185b6ac
            client-secret: 4f9919b70096e97cd156100da3065bbdb11cd0f3
            scope:
              - read:user
              - notifications
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
          gitlab:
            client-id: 654e38491e3cade51fda4423c4b9073bc9b7c87fd83ca9c4b7039230179469ca
            client-secret: 692a260a4f6b0a6a2f9b46c21e2dddc3aa9ec03c0e0d222e0ea13b4fc658a345
            authorization-grant-type: authorization_code
            scope:
              - read:user
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            clientName: GitLab
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/oauth/userinfo
            jwk-set-uri: https://gitlab.com/oauth/discovery/keys
github:
  base:
    url: https://api.github.com/

gitlab:
  base:
    url: https://gitlab.com/api/

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

server:
  port: 9090