spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: af73a9da1cbda378e51f
            client-secret: d20bcd63402bb90af1cb2c74fac1241a5563b02e
            scope:
              - read:user
              - notifications
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
github:
  base:
    url: https://api.github.com/

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

server:
  port: 9090